### ISSUE TITLE
Host header causing traceback

### ISSUE THREAD

**Issue by focrensh** [jgruberf5/ViaUATEndpoint#2]
# Error
```
INFO:     172.17.0.1:58528 - "GET /favicon.ico HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/./main.py", line 598, in get_response
    return apply_policy(request, response)
  File "/app/./main.py", line 445, in apply_policy
    policy_match_hash = utils.get_matched_policy_hash(
  File "/app/./utils.py", line 370, in get_matched_policy_hash
    header_match_value = header[header_name]
KeyError: 'host'
```

# Config
```
[
  {
    "id": 0,
    "ip_version": 4,
    "src_cidr": "ALL",
    "env": [],
    "env_match_policy": "AND",
    "method": "ANY",
    "headers": [],
    "header_match_policy": "AND",
    "path_re_match": "ALL",
    "query": [],
    "query_match_policy": "AND",
    "day_of_week": "ANY",
    "start_time": "",
    "stop_time": "",
    "reply_scripts": [
      {
        "delay_ms": 0,
        "repeat": 0,
        "inject_headers": [],
        "action": "direct_response",
        "direct_response_status_code": 200,
        "direct_response_mime_type": "application/json",
        "direct_response_body": "{\"method\":\"get\",\"config\":\"global_generic_service\"}",
        "direct_response_body_encoding": "NONE",
        "redirect_status_code": 307,
        "redirect_url": "NONE",
        "serve_local_file_path": "NONE",
        "proxy_url": "NONE"
      }
    ]
  },
  {
    "id": 1,
    "ip_version": 4,
    "src_cidr": "ALL",
    "env": [],
    "env_match_policy": "AND",
    "method": "ANY",
    "headers": [
      {"Host": "payroll.v.appinsights.io"}
    ],
    "header_match_policy": "AND",
    "path_re_match": "ALL",
    "query": [],
    "query_match_policy": "AND",
    "day_of_week": "ANY",
    "start_time": "",
    "stop_time": "",
    "reply_scripts": [
      {
        "delay_ms": 0,
        "repeat": 0,
        "inject_headers": [],
        "action": "direct_response",
        "direct_response_status_code": 200,
        "direct_response_mime_type": "application/json",
        "direct_response_body": "{\"method\":\"get\",\"config\":\"payroll-header\"}",
        "direct_response_body_encoding": "NONE",
        "redirect_status_code": 307,
        "redirect_url": "NONE",
        "serve_local_file_path": "NONE",
        "proxy_url": "NONE"
      }
    ]
  }
]
```

**Comment by jgruberf5** [comment]
Previous, the undocumented expected behavior is that all header names in the policy would be lower case.

Now header name matching is case insensative:

https://github.com/jgruberf5/ViaUATEndpoint/commit/0a6dbe0e3075362a8bd760a54bbdfb8e7fe5f661

Local build pushed to dockerhub. Please test..

**Comment by jgruberf5** [comment]
Assuming working... closing..

**Comment by focrensh** [comment]
Yes, no longer caused traceback. Thanks
